### PR TITLE
#89 Display Package Version

### PR DESCRIPTION
**Pull request by brewhousedigital**
Added the package version to the logo.

Not sure if this is the best way to do this. Did a bit of research and found out that importing package info can be a little picky on how its defined. 

Setting value with `JSON.stringify()` seems to help make sure its the right variable type when passed through Vite. https://stackoverflow.com/questions/67707813/defining-global-variables-with-vite-development#answer-67708431

And the import statements came from the SvelteKit FAQ though theirs was based in the `svelte.config.js` file and I had to use `vite.config.ts` to get it to work right. Not sure why. https://kit.svelte.dev/faq#read-package-json

image

image

## P.S.

If you modify the `package.json` version number, you have to restart the server or `vite.config.ts` won't pick up the changes

### CODE REVIEW

**Comment by benallfree** [comment]
You know... I'm thinking it might be better to just supply an environment variable with the version string. Relying on the package.json doesn't feel like the right idea to me, because the "version" isn't just the frontend version or the backend version, it is a combined monorepo release.

So either an environment variable or the `version` from the root package.json.

What do you think?

**Comment by brewhousedigital** [comment]
Either should work. env might be more performant since we don't need NodeJS's filesystem for it. Do you use the versioning for anything on the backend side?

**Comment by benallfree** [comment]
Let's go with modifying `src/env.ts` and using a `PUBLIC_POCKETHOST_VERSION=0.4.1` or whatever in `.env-template`

Thank you for doing another round on this!

**Comment by brewhousedigital** [comment]
Updated `env.ts`, added the new env variable name to the template and to my local `.env` file. 

Removed all the file system stuff.

**Pull request merged**
