### PR TITLE
Added new Navbar, Login/Register pages, and new Components

### PR DESCRIPTION
**Pull request by brewhousedigital**
## Summary 
Lots of fun updates:

- New `AlertBar` component
- Added new design border to the homepage hero animation
- New `InstanceGeneratorWidget` that will create a new account, log the user in, and then create the instance for them all at once.
- Rebuilt the navigation bar
- Moved all the database and authentication logic to the `database.ts` file for better reusability and added JSDoc 
- The homepage will show different CTAs depending on if you are logged in or not
- Built new Login and Register pages
- Created a new `stores.ts` file for Svelte Stores. I'm not using this now but we may use it later.
- Created a new `utilities.ts` file to store reusable functions. Will move the `redirect()` call there at some point
- Added some new theme updates to the `global.css` file

## Bug Fixes
- The `type="text/scss"` has been deprecated and has been changed to `lang="scss"`
- Added default values to the new `FeatureCard` component
- Removed some global CSS so that each page has more control over it's design

## What's Next?

Anything you needed changed, just let me know. I am definitely not a color expert so if you dislike the colors / gradients, feel free to send over new ones and I'll update them for ya! The ones that are on the site are taken from this website here: [https://gradienthunt.com/popular](https://gradienthunt.com/popular)

I modified the logo, but I can revert that back, just let me know. 

Next on the list is the Dashboard and Instances pages.

Let me know what your thoughts are on how I organized everything and if you'd prefer something different. Feedback is highly appreciated!!

### CODE REVIEW

**Comment by benallfree** [comment]
Wow, I'm really in love with all of this! That home page signup is perfect, nice job.

Since I can't push to your branch, I made a PR against this PR :) https://github.com/brewhousedigital/pockethost/pull/1

Apparently a couple things were broken, I got them working how they're supposed to again.

Hey one question, are you using the `prettier` settings to format your code? I noticed that the new files you made used different indentation rules. How can we sync up on code formatting?

**Comment by benallfree** [comment]
PS, I personally like the colors. Especially the demo box, it has kind of a retro feel that reminds me of my old Atari 2600 :D

**Comment by benallfree** [comment]
FYI I have been using a mobile-first approach on this site where I design for the smallest device size first and then expand out from there. The home page needs some adjusting.

image

image

**Comment by brewhousedigital** [comment]
- PR merged!
- Great about the bug fixes! 
- I noticed the formatting too. My local code doesn't look like the github code so I assumed github was doing something weird. I'll make sure prettier is turned on and in sync.
- I really liked the demo box too! Glad you felt the same.
- Good catch on the mobile. I haven't looked at that part yet. I'll go through and make sure it's as mobile friendly as possible. Do you expect most of your users to be on mobile?
- If there is an error with the `InstanceGeneratorWidget`, it was showing an error message for me, is it not anymore? I'll investigate.

**Comment by benallfree** [comment]
> I'll make sure prettier is turned on and in sync.

If you merge from `master`, I've added a github action that tests each commit using `prettier` so it'll catch formatting stuff. There is also a `yarn prettier:fix` in the repo root that will run through everything. I think those two things should prevent further issues even if your code editor doesn't pick it up automatically. Are you using VSCode or something else?

> Do you expect most of your users to be on mobile?

I have no data, but my intuition is that it is probably common enough to address. That said, I program and mess with PocketBase most often on my laptop :)

> `InstanceGeneratorWidget`

I'm going to do more work on this since I was the last one to touch the error handling. It's a little complex because there are 3 separate steps and they're not in a transaction so failures can leave things in an intermediate state. If I were far enough along on `PBScript` I could make an `/api/instant-signup` endpoint that created the user account, created the instance entry, and logged them in all in one transaction.

**Comment by brewhousedigital** [comment]
## Updates

- Prettier tested and working great
- Mobile styles added for the homepage now (my commit says dashboard, i meant to say homepage)
- For the mobile homepage, I'm wondering if we should hide the animation in general. It takes up a lot of screen real estate and users will miss the animation anyways since its below the fold. What are your thoughts?

## Error Handling

Great points about the error handling. Would it be possible to have a `GET` request just for the name and it have it return back a true/false for if its available? That way we could continue with the registration/signup without any worry?

The transaction stuff is totally right. If left on the UI side, I wonder if we could utilize a Svelte Store + `localStorage` to keep track of it all, until the final step has been completed, then we just clear it and the user is good to go? Otherwise a backend service that could handle retries would also be nice. 

I'll work on the mobile nav now. I intentionally left that one un-designed cause I was thinking of a better way to handle the dropdowns. I could use CSS to hide/show different navbars but thats not good for HTML semantics. I'm going to see if there's some Svelte media query hook that will actually remove the HTML from the DOM depending on screen size. That'd be the most SEO friendly.

**Comment by benallfree** [comment]
FYI https://github.com/brewhousedigital/pockethost/pull/2/ is pending

> hide the animation

Hmm, probably! Anyway we can try it hidden. Or make a mobile-friendly version of it? I love the idea of it in general, it makes so much sense. Or what if mobile had a 'get started' that popped a modal with the signup+instance form?

> Would it be possible to have a GET request just for the name and it have it return back a true/false for if its available?
> The transaction stuff is totally right.

I *think* I have it covered in my latest PR above. But yes we could do some client-side validation so it doesn't suggest a name that's already taken (super unlikely but random) or maybe checks as they type. That could be cool. I think there is a `getInstanceBySubdomain` already available that you could use in the validator callback.

> better way to handle the dropdowns

Yes feel free to get creative, I'm very open to ideas and I 💯 love everything you've done so far! Thank you so much for supporting this project and giving it some curb appeal. I know it will boost peoples' confidence and help the idea click. I think this is an important project for PocketBase even if it is a bet antithetical to the 'one compile, one file' philosophy of the core project. A turnkey way to get started is a huge win for Firebase and Supabase and I don't want us to miss out on that idea... AND, eventually PocketHost might be able to run custom binaries as well.

**Comment by brewhousedigital** [comment]
## Updates

- Removed the homepage animation off mobile. It's there in tablet and up
- Improved the navigation dropdown on mobile by centering the links, and adding the 'Github' text when viewed on a phone
- Added a new `<MediaQuery>` component. This will help us on the SEO side since DOM elements will be removed instead of hidden. Navigation content is a little duplicated but that usually happens when you have a radically different desktop vs mobile nav bar.
- Merged all the PRs together, and updated the fork from your main branch.

Let me know what's next or if this PR looks good to you! I'm having a blast working on this. 🎉

## Ideas

- What do you think about changing from that sliding dropdown to using a mobile slide out menu? Those look flashy right? I can experiment if you're interested.

## Funny

Prettier is drunk if it thinks this looks ok, lol

image

**Comment by benallfree** [comment]
> Prettier is drunk

lol yes I’ve noticed that too. It seems to be an artifact of the prettier svelte plug-in. I wonder if there is a setting for it. 

I’ll look at the rest tomorrow, thanks so much!

**Comment by benallfree** [comment]
OK this seems great! I merged it just so our PRs don't get too big and I'll probably go ahead and deploy this much in the next release. 

* noticed that the `profile` and `settings` menus 404 (expected). We might think about removing that before the next update
* I really miss the homepage animation, i wonder if making it a little smaller on mobile would be good enough? Right below the "spend less time...", then have the signup below the fold? Just a thought.

Other than that, I'd love to see you take a crack at the dashboard. In particular, notice that the status message dynamically changes from 'idle' to 'running' if you do something like launch the admin. That's a realtime indicator. Idle means everything is good but it's not presently running in memory because there is no traffic to that instance.

**Pull request merged**
