### PR TITLE
#17 Added Open Graph to the site

### PR DESCRIPTION
**Pull request by brewhousedigital**
# Open Graph

Added poster image, and sharing tags

# Twitter Tags

Added sharing tags

# Pages

Added custom titles per page

# Manifest File

If we ever want to market this as an installable web app, the `manifest.json` file is the first step

### CODE REVIEW

**Comment by benallfree** [comment]
If you have time could you add screenshots for Facebook and Twitter?

**Comment by brewhousedigital** [comment]
@benallfree  This is the poster image that will show up on facebook/twitter/discord/other:

https://github.com/benallfree/pockethost/pull/34/files#diff-927f72a0582fc2b84cbd9f03fe2724939eb69310e27568cd842772e1ea26ac1f

or did you mean something else?

**Comment by benallfree** [comment]
Oh yeah I was just curious to see what it actually looked like in a FB or Twitter feed. But that’s okay I can test it with ngrok.

**Comment by benallfree** [comment]
Hmm, I think part of the issue is that the host name is hard-coded in app.html

A better approach might be to do something similar to my darkmode fix with `<svelte:head>` in `+layout.svelte`. From there, you could pull `PUBLIC_APP_DOMAIN` like https://github.com/benallfree/pockethost/blob/master/packages/pockethost.io/src/routes/+page.svelte

We may also need to introduce a `PUBLIC_HTTP_PROTOCOL` which is either `http` or `https`

**Comment by benallfree** [comment]
So the only issue I still can’ figure out is Twitter doesn’t seem to be displaying the image. Can you test this please?

**Comment by brewhousedigital** [comment]
Could Twitter be blocking the tunnel? The good news is, pushing this live wouldn't break anything on the UI. It's kinda set up to "if its there, use it. if not, ignore it". Might be easier to test with a live site maybe?

**Comment by benallfree** [comment]
Merged! https://github.com/benallfree/pockethost/commit/5c8903fac6877e9e380b2daa46452d44bfc2b918

**Pull request closed without merging**
