### PR TITLE
Added the New Dashboard and Instances Pages

### PR DESCRIPTION
**Pull request by brewhousedigital**
# New Pages

## Dashboard - No Apps

There's a big CTA front-and-center to direct new users to creating their new app

image

## Dashboard - With Apps

The new apps will show up here with CTAs directing them to the details or to their Pocketbase admin panels. They also have a CTA at the bottom prompting them to create new apps.

image

## Add Instance

Front-and-center form to create a new instance. This was modified to be a `<form>` element so its more accessible, and the logic was off-loaded to the `database.ts` file so everythings nice and neat.

image

## Instance Details

Details wasn't updated much. I assume this will be expanded down the road with charts/statuses?

image

## Components

Rebuilt the Provision Status badge to be javascript based instead of CSS based. Also added a fun pulsing effect to let you know when the server is running.

## Other

Added some more CSS theming, and added the PocketBase logo.

## Todo at some point

Need to turn the cool multi-colored border box into it's own component so we can reuse it. Declaring the giant block of CSS over and over might get messy.

## Next Up

Let me know what you think so far!

If this looks good, my next PR will be to remove SvelteStrap completely, and to get rid of any unused files. There's also a bug I found this morning with the mobile navigation. When you click on a link, it doesn't close the nav. So i'll get that fixed as well.

### CODE REVIEW

**Comment by benallfree** [comment]
🤯🤯🤯 so good! I’m reviewing this on my phone and it already looks amazing! Can’t wait to get home and give it a test run.

**Comment by benallfree** [comment]
Ps I love the stacking visual effect. Very tasteful.

**Comment by benallfree** [comment]
@brewhousedigital This is fantastic, thank you so much for continuing your efforts here. I think it will make a big impact on how people perceive the project and how willing they are to trust it and use it.

> If this looks good, my next PR will be to remove SvelteStrap completely, and to get rid of any unused files.

Awesome! Goodbye popperjs!

> There's also a bug I found this morning with the mobile navigation. When you click on a link, it doesn't close the nav. So i'll get that fixed as well.

👍 

I'm not super knowledgeable about SvelteKit, but is there a way to redirect without using `window.location`? That seems to reload the entire page and feels much slower. For example, transitioning from the home page to the dashboard when using the instance creation widget on the home page. That causes a full page reload. Any ideas on how to fix this?

**Comment by brewhousedigital** [comment]
> is there a way to redirect without using window.location?

@benallfree Thanks for the reminder. I left a note here to refactor this to use SvelteKit's router instead of a hard refresh

https://github.com/benallfree/pockethost/blob/master/packages/pockethost.io/src/util/redirect.ts#L1

**Pull request merged**
