### PR TITLE
fix: frontend docs cosmetics

### LINKED ISSUE #173: Frontend docs cosmetics
For @brewhousedigital

### PR DESCRIPTION
**Pull request by AmmarR0118**
this pull request fixes #173

### CODE REVIEW

**Comment by benallfree** [comment]
@AmmarR0118 I’m traveling and will review asap. 

For faster review, can you post some screen shots in both mobile and desktop responsive modes?

Also, I see you added an app.css. What is the purpose of that? Is it meant to be css local to the docs section?

**Comment by AmmarR0118** [comment]
@benallfree
desktop view
desktop
mobile view
mobile

**Comment by AmmarR0118** [comment]
i removed the app.css. it was just styling scrollbar

**Comment by benallfree** [comment]
This looks awesome!! Did you test it in dark mode?

**Comment by AmmarR0118** [comment]
@benallfree i fixed the dark mode. this is how it looks in mobile and desktop
dark_mode_desktop
light_mode_desktop
dark_mode_mobile
light_mode_mobile

**Pull request closed without merging**
