### PR TITLE
FAQ component prototype

### PR DESCRIPTION
**Pull request by shaparder**
## Scope

Following #37, I worked on a FAQ section for the website. At the moment it is displayed on the homepage because the UI fits well this use case.

## Implementation

The changes are minor so they are easy to review. Here are the file modifications:

[**NEW FILE**] $/components/FrequentlyAskedQuestions.svelte:
- New component file in the components directory.
- The code is pretty self explanatory, nothing crazy. Just using bootstrap and some TS logic to display a list of questions/answers dynamically.
- The questions have a *collapsed* attribute, when set to false, the answer is displayed.

[**UPDATE**] packages/pockethost.io/src/routes/+page.svelte:
- Added an import to import the svelte component
- Added a few lines at the end to display the component
- Changed some styles and class names for styling consistence purposes (features and section)

## Pitfalls
1. I wasn't sure what to write as answers for the questions, might need some changes to be more accurate.
2. The style matches the homepage, so far it is displayed there. Might need a light rework if used in the Docs.

## Conclusion

@brewhousedigital @benallfree feel free to provide feedback !

### CODE REVIEW

**Comment by benallfree** [comment]
@shaparder Thank you so much for this contribution!

A couple thoughts:

1. Is there a way to integrate this with the `/docs` experience? https://github.com/benallfree/pockethost/issues/37#issuecomment-1387490687
2. If possible, please post a screen shot in this PR so we can take a look without pulling the branch. It will make preliminary review faster.

**Comment by shaparder** [comment]
> @shaparder Thank you so much for this contribution!

The pleasure is mine ! I'd like to see this project grow, even if I can't help much on the core infrastructure yet. 

 
> A couple thoughts:
> 
> 1. Is there a way to integrate this with the `/docs` experience? [FAQ page? #37 (comment)](https://github.com/benallfree/pockethost/issues/37#issuecomment-1387490687)

Yes, as said in the end of the PR: the styling matches the one of the homepage, not the docs (albeit the docs have quite not much styling at all, so it could just be used there)

Using the component in the Docs is as simple as importing the component and calling it from the Docs file:
`
// importing the component
import FrequentlyAskedQuestions from '$components/FrequentlyAskedQuestions.svelte'

// instantiating it
<FrequentlyAskedQuestions />
`

Wrapping it in a container for padding / 

> 2. If possible, please post a screen shot in this PR so we can take a look without pulling the branch. It will make preliminary review faster.

Sorry about that, thought about doing it but it's the same as the one in #37 so I didn't actually provide one, here it is:

Screenshot 2023-01-24 at 13 01 18

**Comment by shaparder** [comment]
Quick update: I just pushed the modification where the FAQ is in the Docs, this it what it looks like:
Screenshot 2023-01-24 at 13 32 53

Style does not fit superbly but it works, maybe it would make more sense to just write it as a .md file like the rest of the Docs and keep the component for the homepage as I really think FAQs can be powerful marketing tools ?

**Comment by benallfree** [comment]
@shaparder This is really great work, thank you!

Please pull the latest from `master` and run `yarn` to update packages. I have added `routes/docs/pages/faq.md` which can be imported as:

```ts
import { faq } from '$src/docs`
```

The `faq` object has the following fields:

```json
{
  "attributes": {
    "title": "Frequently Asked Questions"
  },
  "body": "...entire body...",
  "outline": [
    {
      "title": "Question 1",
      "body": "\n<p>answer 2</p>\n"
    },
    {
      "title": "Question 2",
      "body": "\n<p>answer 2</p>\n"
    }
  ]
}
```

My suggestion is to decouple the FAQ items from the component. 

Please update `src/docs/faq.md` with all the FAQ content, and then use the `faq.outline` field to iterate through all the questions, displaying `title` and `body` for each in your component. Then we would truly have a FAQ component that could display whatever the latest FAQ items were, while also being able to use the same FAQ content in the `docs/` section of the site.

Let me know if that makes sense!

**Comment by shaparder** [comment]
Hi, thanks for your answer ! Decoupling is definitely the way to go, but in doing so, when adding the faq.md file the Docs are automatically generated and the `/docs/faq` route is taken by this file and I can't use it anymore.

Furthermore, I'm not experienced when working with `.md` files in Javascript. However, it seems the structure imported through `src/docs/faq.md` looks like this:
```

```

**Comment by shaparder** [comment]
I'm sorry to waste your time, I didn't run yarn at the top level smh, that's my bad ! Alright this is working fine now.
Screenshot 2023-01-24 at 17 21 04

I'm going to style it a little bit more and push it ! Thanks for your help

**Comment by shaparder** [comment]
Here's the final look. Thanks for your patience ! I don't have much more time as for now, maybe i'll come back to work on some UI in the coming weeks !
Screenshot 2023-01-24 at 17 33 39

**Comment by benallfree** [comment]
> add a form underneath for people to ask their questions

Cool idea!

Okay, I'll go ahead and merge this. Thank you so much for your contribution! The community is better for it.

**Pull request merged**
